### ISSUE TITLE
Reduce confusions with next button in tutorial

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/training-app#61]
## Tasks

- [x] Update previous and next buttons in tutorial dialog
  - [x] When jumping to a step: Text should be ``Next step`` or ``Previous step`` with a Blue fill.
  - [x] When jumping to a sub-step: Text should be ``Next`` or ``Previous`` with an Orange fill.
- [x] Change sub-step bullet fill to Orange
- [x] Move colors to new constants file as asset

## Resources

Blue hex color: ``#43CBCB``
Orange hex color: ``#FF8F02``

## Screenshots

Before:
![image](https://user-images.githubusercontent.com/2181866/98150917-ab8adc80-1ecf-11eb-8f17-45a811b49ff1.png)

After:
![image](https://user-images.githubusercontent.com/2181866/98150741-6cf52200-1ecf-11eb-8a52-d231a131d8b6.png)
